# Generated by Django 2.0.3 on 2018-04-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
                ('publishDate', models.DateField()),
                ('edition', models.IntegerField()),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
